# Generated by Django 2.1.5 on 2019-02-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mather_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('dob', models.DateField(auto_now_add=True)),
                ('age', models.IntegerField(default=0)),
                ('_class', models.IntegerField(default=0)),
                ('Speaks_Kannada', models.BooleanField(default=False)),
            ],
        ),
    ]
